name: "Run Conformance Tests"

# Événements sur lesquels il doit être déclenché
on:
  workflow_dispatch: # <- Manuellement
  #push:         # <- Déclenché lorsque l'on pousse du code...
  # branches:
  #   - master  # <- ... mais seulement sur cette branche

jobs:
  conformance-tests: # <- Nom du job
    runs-on: vrunner-antibois
    container: golang
    steps:  
      - 
        name: "Checkout"
        uses: actions/checkout@v3
      -
        name: "Update"
        run: |
          apt update -y
          apt install -y rsync
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: "Clone Kubernetes"
        run: |
          git clone --recurse-submodules --branch=v1.28.1 --depth=1 https://github.com/kubernetes/kubernetes
      -
        name: "Build kubernetes node-image"
        run: |
          go install sigs.k8s.io/kind@v0.20.0
          cd kubernetes
          kind build node-image
          docker images
      - 
        name: "Create the cluster"
        run: |
          cat << EOF > kind-config.yaml
          # necessary for conformance
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          networking:
            ipFamily: ipv4
          nodes:
          # the control plane node
          - role: control-plane
          - role: worker
          - role: worker
          EOF
          KUBECONFIG="${HOME}/.kube/kind-test-config"
          echo "KUBECONFIG=${HOME}/.kube/kind-test-config" >> GITHUB_ENV
          kind create cluster --config kind-config.yaml --image kindest/node:latest -v4
      -
        name: "Create the e2e Kubernetes binary"
        run: |
          pwd
          cd ~/src/k8s.io/kubernetes
          pwd
          make WHAT="cmd/kubectl"
          make WHAT="vendor/github.com/onsi/ginkgo/ginkgo"
          make WHAT="test/e2e/e2e.test"
          pwd
          echo "find e2e.test"
          find . -name "e2e*"
      -
        name: "Run the tests"
        run: |
          kubectl get nodes
          kubectl cluster-info --context kind-kind
          ./_output/bin/e2e.test -context kind-kind -ginkgo.focus="\[sig-network\].*Conformance" -num-nodes 2
    
