name: "Run Conformance Tests"

# Événements sur lesquels il doit être déclenché
on:
  workflow_dispatch: # <- Manuellement
  #push:         # <- Déclenché lorsque l'on pousse du code...
  # branches:
  #   - master  # <- ... mais seulement sur cette branche

jobs:
  conformance-tests: # <- Nom du job
    runs-on: vrunner-antibois
    # container: golang
    steps:
      -
        name: "Update"
        run: |
          sudo apt update -y
          sudo apt install -y golang make apt-transport-https ca-certificates curl
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
          # For AMD64 / x86_64
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          # For ARM64
          [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - 
        name: "Checkout"
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: "Clone Kubernetes"
        run: |
          git clone --recurse-submodules --branch=v1.28.1 --depth=1 https://github.com/kubernetes/kubernetes
      -
        name: "Build kubernetes node-image"
        run: |
          cd kubernetes
          kind build node-image
          docker images
      - 
        name: "Create the cluster"
        run: |
          cat << EOF > kind-config.yaml
          # necessary for conformance
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          networking:
            ipFamily: ipv4
          nodes:
          # the control plane node
          - role: control-plane
          - role: worker
          - role: worker
          EOF
          KUBECONFIG="${HOME}/.kube/kind-test-config"
          echo "KUBECONFIG=${HOME}/.kube/kind-test-config" >> GITHUB_ENV
          kind create cluster --config kind-config.yaml --image kindest/node:latest -v4
      -
        name: "Create the e2e Kubernetes binary"
        run: |
          pwd
          cd kubernetes
          pwd
          make WHAT="cmd/kubectl"
          make WHAT="vendor/github.com/onsi/ginkgo/ginkgo"
          make WHAT="test/e2e/e2e.test"
          pwd
          echo "find e2e.test"
          find . -name "e2e*"
      -
        name: "Run the tests"
        run: |
          kubectl get nodes
          kubectl cluster-info --context kind-kind
          ./_output/bin/e2e.test -context kind-kind -ginkgo.focus="\[sig-network\].*Conformance" -num-nodes 2
    
